-- local M = {}
--
-- function M.setup()
--   local lspconfig = require("lspconfig")
--   local configs = require("lspconfig.configs")
--
--   -- Register echo_lsp as a custom server if not already registered
--   if not configs.echo_lsp then
--     configs.echo_lsp = {
--       default_config = {
--         cmd = {
--           vim.fn.stdpath("data") .. "/lazy/echo_lsp_server/scripts/launch.sh",
--         },
--         filetypes = { "text", "markdown", "lua", "python", "javascript", "typescript" },
--         root_dir = function(fname)
--           return vim.fn.getcwd()
--         end,
--         settings = {},
--         single_file_support = true,
--       },
--       docs = {
--         description = "Simple Echo LSP Server for testing",
--       },
--     }
--   end
-- end
--
-- return M
